import type { DeployConfig } from '../types/index.js'

interface DeployResult {
  success: boolean
  url?: string
  instructions: string
  error?: string
}

export class Deployer {
  async deploy(
    botName: string,
    workspaceDir: string,
    config: DeployConfig,
  ): Promise<DeployResult> {
    switch (config.type) {
      case 'docker':
        return this.deployDocker(botName, workspaceDir, config)
      case 'fly':
        return this.deployFly(botName, workspaceDir, config)
      case 'railway':
        return this.deployRailway(botName, workspaceDir, config)
      case 'self-hosted':
        return this.deploySelfHosted(botName, workspaceDir, config)
      default:
        return {
          success: false,
          instructions: 'Unknown deployment type',
          error: `Unsupported deployment type: ${config.type}`,
        }
    }
  }

  private async deployDocker(
    botName: string,
    workspaceDir: string,
    config: DeployConfig,
  ): Promise<DeployResult> {
    // Build and optionally push Docker image
    return {
      success: true,
      instructions: `Deploy with Docker:

cd ${workspaceDir}
docker build -t ${botName} .
docker run -d \\
  -e BOT_TOKEN=${config.botToken} \\
  ${Object.entries(config.env)
    .map(([k, v]) => `  -e ${k}=${v} \\`)
    .join('\n')}
  ${botName}

Or push to a registry and deploy on any cloud:

docker tag ${botName} ghcr.io/your-org/${botName}
docker push ghcr.io/your-org/${botName}`,
    }
  }

  private async deployFly(
    botName: string,
    workspaceDir: string,
    config: DeployConfig,
  ): Promise<DeployResult> {
    return {
      success: true,
      instructions: `Deploy to Fly.io:

cd ${workspaceDir}
flyctl launch --name ${botName} --no-deploy
flyctl secrets set BOT_TOKEN=${config.botToken}
${Object.entries(config.env)
  .map(([k, v]) => `flyctl secrets set ${k}=${v}`)
  .join('\n')}
flyctl deploy`,
    }
  }

  private async deployRailway(
    botName: string,
    workspaceDir: string,
    config: DeployConfig,
  ): Promise<DeployResult> {
    return {
      success: true,
      instructions: `Deploy to Railway:

cd ${workspaceDir}
railway login
railway init
railway up
railway domain

Then set environment variables in Railway dashboard:
- BOT_TOKEN=${config.botToken}
${Object.entries(config.env)
  .map(([k, v]) => `- ${k}=${v}`)
  .join('\n')}`,
    }
  }

  private async deploySelfHosted(
    botName: string,
    workspaceDir: string,
    config: DeployConfig,
  ): Promise<DeployResult> {
    return {
      success: true,
      instructions: `Deploy to your own server:

1. Copy the workspace to your server:
   scp -r ${workspaceDir} user@your-server:/opt/${botName}

2. SSH into your server and run:
   cd /opt/${botName}
   docker compose up -d

3. Set environment variables:
   - BOT_TOKEN=${config.botToken}
${Object.entries(config.env)
  .map(([k, v]) => `   - ${k}=${v}`)
  .join('\n')}

4. Ensure the bot is running:
   docker compose logs -f`,
    }
  }

  generateDeployScript(botName: string, config: DeployConfig): string {
    return `#!/bin/bash
# Deploy script for ${botName}
# Generated by Bot Foundry

set -euo pipefail

BOT_TOKEN="${config.botToken}"

echo "Deploying ${botName}..."

# Build
docker build -t ${botName} .

# Run
docker run -d --restart always \\
  --name ${botName} \\
  -e BOT_TOKEN=\$BOT_TOKEN \\
  ${Object.entries(config.env)
    .map(([k, v]) => `  -e ${k}=${v} \\`)
    .join('\n')}
  ${botName}

echo "✅ ${botName} deployed successfully"
`
  }
}
